
[window]
opacity = 0.90
decorations = "buttonless"
startup_mode = "Fullscreen"
padding = { x = 10, y = 10 }
# blur=true
# animation = "EaseOutExpo" #=>works in unofficial build
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13.0

[colors.primary]
background = "0x0f0f0f"
foreground = "0xe0e0e0"

[colors.cursor]
text = "#ff5000"
cursor = "#ff4500"

[cursor]
style = "Beam"

[keyboard]
bindings = [
  { key = "N", mods = "Command", action = "SpawnNewInstance" },
  { key = "F", mods = "Command", action = "ToggleFullscreen" },
]

[bell]
animation = "EaseOutQuad"
duration = 200
color = "#ff4500"

